name: ARCHE Metadata Ingest

on:
  workflow_dispatch

jobs:
  build_pages_and_ingest:
    name: ARCHE Ingest
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
    steps:
    - name: get data
      run: |
        echo "do something to get your data"
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: install python packages
      run: |
        pip install -U pip
        pip install -r requirements.txt
    - name: Install Saxon and ANT
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
        echo "downloading saxon"
        wget https://sourceforge.net/projects/saxon/files/Saxon-HE/9.9/SaxonHE9-9-1-7J.zip/download && unzip download -d saxon && rm -rf download
    - name: Fetch Data
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        ./fetch_data.sh
        ./delete_schema.sh
    - name: Build
      run: |
        ant -f build_arche.xml
    - name: ingestion dependencies
      run: |
        composer require "acdh-oeaw/arche-ingest:^1"
    - name: ingest arche-cases
      run: |
        vendor/bin/arche-import-metadata html/arche-cases.rdf https://arche-dev.acdh-dev.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}}
    - name: ingest resources
      run: |
        vendor/bin/arche-import-metadata html/arche.rdf https://arche-dev.acdh-dev.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}} --retriesOnConflict 25
    # - name: ingest additional case-md
    #   run: |
    #     vendor/bin/arche-import-metadata html/arche-cases2.rdf https://arche-dev.acdh-dev.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}} --retriesOnConflict 25
    # - name: ingest boehm
    #   run: |
    #     vendor/bin/arche-import-metadata html/arche-boehm.rdf https://arche-dev.acdh-dev.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}} --retriesOnConflict 25
    # - name: ingest Indices MD
    #   run: |
    #     vendor/bin/arche-import-metadata html/arche-indices.rdf https://arche-dev.acdh-dev.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}}
    # - name: Copy XML Files to to_ingest 
    #   run: |
    #     mkdir $PWD/to_ingest
    #     cp cases-index.json ./to_ingest/ 
    #     find -path "./data/editions/*.xml" -exec cp -prv '{}' './to_ingest' ';'
    #     find -path "./data/cases_tei/*.xml" -exec cp -prv '{}' './to_ingest' ';'
    #     find -path "./data/indices/*.xml" -exec cp -prv '{}' './to_ingest' ';'
    #     find -path "./boehm_tei/*.xml" -exec cp -prv '{}' './to_ingest' ';'
    # - name: install repo-file-checker
    #   run: |
    #     composer require "acdh-oeaw/repo-file-checker:^2"
    #     mkdir -p filechecker/tmp filechecker/reports
    # - name: run repo-file-checker
    #   run: |
    #     php -f vendor/acdh-oeaw/repo-file-checker/index.php -- --tmpDir filechecker/tmp --reportDir filechecker/reports to_ingest 0
    # - name: ingest binaries
    #   run: |
    #     vendor/bin/arche-import-binary to_ingest https://id.acdh.oeaw.ac.at/legalkraus https://arche-dev.acdh-dev.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}} --skip not_exist
